name: pytorch-ig
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.14.0
  - freetype=2.12.1
  - gmp=6.3.0
  - gnutls=3.6.13
  - icu=73.2
  - idna=3.7
  - jinja2=3.1.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libpng=1.6.43
  - libsqlite=3.45.3
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - mkl=2022.2.1
  - mpmath=1.3.0
  - ncurses=6.4.20240210
  - nettle=3.6
  - networkx=3.3
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.0
  - pillow=10.3.0
  - pip=24.0
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.12.3
  - python_abi=3.12
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.5.1
  - sympy=1.12
  - tbb=2021.12.0
  - tk=8.6.13
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - typing_extensions=4.11.0
  - urllib3=2.2.1
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.51.0
      - kiwisolver==1.4.5
      - matplotlib==3.8.4
      - packaging==24.0
      - pandas==2.2.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - six==1.16.0
      - tzdata==2024.1
